/*
 * This file is generated by jOOQ.
 */
package com.dw2.reserva.persistence.jooq.tables;


import com.dw2.reserva.persistence.jooq.DefaultSchema;
import com.dw2.reserva.persistence.jooq.Indexes;
import com.dw2.reserva.persistence.jooq.tables.records.LaboratoryRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Laboratory extends TableImpl<LaboratoryRecord> {

    private static final long serialVersionUID = -1599214191;

    /**
     * The reference instance of <code>laboratory</code>
     */
    public static final Laboratory LABORATORY = new Laboratory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LaboratoryRecord> getRecordType() {
        return LaboratoryRecord.class;
    }

    /**
     * The column <code>laboratory.id</code>.
     */
    public final TableField<LaboratoryRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>laboratory.name</code>.
     */
    public final TableField<LaboratoryRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * Create a <code>laboratory</code> table reference
     */
    public Laboratory() {
        this(DSL.name("laboratory"), null);
    }

    /**
     * Create an aliased <code>laboratory</code> table reference
     */
    public Laboratory(String alias) {
        this(DSL.name(alias), LABORATORY);
    }

    /**
     * Create an aliased <code>laboratory</code> table reference
     */
    public Laboratory(Name alias) {
        this(alias, LABORATORY);
    }

    private Laboratory(Name alias, Table<LaboratoryRecord> aliased) {
        this(alias, aliased, null);
    }

    private Laboratory(Name alias, Table<LaboratoryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.LABORATORY_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<LaboratoryRecord, Integer> getIdentity() {
        return Internal.createIdentity(com.dw2.reserva.persistence.jooq.tables.Laboratory.LABORATORY, com.dw2.reserva.persistence.jooq.tables.Laboratory.LABORATORY.ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<LaboratoryRecord> getPrimaryKey() {
        return Internal.createUniqueKey(com.dw2.reserva.persistence.jooq.tables.Laboratory.LABORATORY, "KEY_laboratory_PRIMARY", com.dw2.reserva.persistence.jooq.tables.Laboratory.LABORATORY.ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<LaboratoryRecord>> getKeys() {
        return Arrays.<UniqueKey<LaboratoryRecord>>asList(
              Internal.createUniqueKey(com.dw2.reserva.persistence.jooq.tables.Laboratory.LABORATORY, "KEY_laboratory_PRIMARY", com.dw2.reserva.persistence.jooq.tables.Laboratory.LABORATORY.ID)
        );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Laboratory as(String alias) {
        return new Laboratory(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Laboratory as(Name alias) {
        return new Laboratory(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Laboratory rename(String name) {
        return new Laboratory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Laboratory rename(Name name) {
        return new Laboratory(name, null);
    }
}
