/*
 * This file is generated by jOOQ.
 */
package com.dw2.reserva.persistence.jooq.tables;


import com.dw2.reserva.persistence.jooq.DefaultSchema;
import com.dw2.reserva.persistence.jooq.Indexes;
import com.dw2.reserva.persistence.jooq.tables.records.LoginRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Login extends TableImpl<LoginRecord> {

    private static final long serialVersionUID = -691997901;

    /**
     * The reference instance of <code>login</code>
     */
    public static final Login LOGIN = new Login();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LoginRecord> getRecordType() {
        return LoginRecord.class;
    }

    /**
     * The column <code>login.email</code>.
     */
    public final TableField<LoginRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>login.password</code>.
     */
    public final TableField<LoginRecord, String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * Create a <code>login</code> table reference
     */
    public Login() {
        this(DSL.name("login"), null);
    }

    /**
     * Create an aliased <code>login</code> table reference
     */
    public Login(String alias) {
        this(DSL.name(alias), LOGIN);
    }

    /**
     * Create an aliased <code>login</code> table reference
     */
    public Login(Name alias) {
        this(alias, LOGIN);
    }

    private Login(Name alias, Table<LoginRecord> aliased) {
        this(alias, aliased, null);
    }

    private Login(Name alias, Table<LoginRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.LOGIN_USER_UK_EMAIL);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<LoginRecord>> getKeys() {
        return Arrays.<UniqueKey<LoginRecord>>asList(
              Internal.createUniqueKey(com.dw2.reserva.persistence.jooq.tables.Login.LOGIN, "KEY_login_user_uk_email", com.dw2.reserva.persistence.jooq.tables.Login.LOGIN.EMAIL)
        );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Login as(String alias) {
        return new Login(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Login as(Name alias) {
        return new Login(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Login rename(String name) {
        return new Login(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Login rename(Name name) {
        return new Login(name, null);
    }
}
