/*
 * This file is generated by jOOQ.
 */
package com.dw2.reserva.persistence.jooq.tables;


import com.dw2.reserva.persistence.jooq.DefaultSchema;
import com.dw2.reserva.persistence.jooq.Indexes;
import com.dw2.reserva.persistence.jooq.tables.records.ReserveLaboratoryRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReserveLaboratory extends TableImpl<ReserveLaboratoryRecord> {

    private static final long serialVersionUID = -114872477;

    /**
     * The reference instance of <code>reserve_laboratory</code>
     */
    public static final ReserveLaboratory RESERVE_LABORATORY = new ReserveLaboratory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReserveLaboratoryRecord> getRecordType() {
        return ReserveLaboratoryRecord.class;
    }

    /**
     * The column <code>reserve_laboratory.id</code>.
     */
    public final TableField<ReserveLaboratoryRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>reserve_laboratory.start_date</code>.
     */
    public final TableField<ReserveLaboratoryRecord, LocalDateTime> START_DATE = createField("start_date", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * The column <code>reserve_laboratory.end_date</code>.
     */
    public final TableField<ReserveLaboratoryRecord, LocalDateTime> END_DATE = createField("end_date", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * The column <code>reserve_laboratory.user_id</code>.
     */
    public final TableField<ReserveLaboratoryRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>reserve_laboratory.laboratory_id</code>.
     */
    public final TableField<ReserveLaboratoryRecord, Integer> LABORATORY_ID = createField("laboratory_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>reserve_laboratory</code> table reference
     */
    public ReserveLaboratory() {
        this(DSL.name("reserve_laboratory"), null);
    }

    /**
     * Create an aliased <code>reserve_laboratory</code> table reference
     */
    public ReserveLaboratory(String alias) {
        this(DSL.name(alias), RESERVE_LABORATORY);
    }

    /**
     * Create an aliased <code>reserve_laboratory</code> table reference
     */
    public ReserveLaboratory(Name alias) {
        this(alias, RESERVE_LABORATORY);
    }

    private ReserveLaboratory(Name alias, Table<ReserveLaboratoryRecord> aliased) {
        this(alias, aliased, null);
    }

    private ReserveLaboratory(Name alias, Table<ReserveLaboratoryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.RESERVE_LABORATORY_PRIMARY, Indexes.RESERVE_LABORATORY_RESERVE_LABORATORY_FK_LABORATORY, Indexes.RESERVE_LABORATORY_RESERVE_LABORATORY_FK_USER);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ReserveLaboratoryRecord, Integer> getIdentity() {
        return Internal.createIdentity(com.dw2.reserva.persistence.jooq.tables.ReserveLaboratory.RESERVE_LABORATORY, com.dw2.reserva.persistence.jooq.tables.ReserveLaboratory.RESERVE_LABORATORY.ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ReserveLaboratoryRecord> getPrimaryKey() {
        return Internal.createUniqueKey(com.dw2.reserva.persistence.jooq.tables.ReserveLaboratory.RESERVE_LABORATORY, "KEY_reserve_laboratory_PRIMARY", com.dw2.reserva.persistence.jooq.tables.ReserveLaboratory.RESERVE_LABORATORY.ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ReserveLaboratoryRecord>> getKeys() {
        return Arrays.<UniqueKey<ReserveLaboratoryRecord>>asList(
              Internal.createUniqueKey(com.dw2.reserva.persistence.jooq.tables.ReserveLaboratory.RESERVE_LABORATORY, "KEY_reserve_laboratory_PRIMARY", com.dw2.reserva.persistence.jooq.tables.ReserveLaboratory.RESERVE_LABORATORY.ID)
        );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReserveLaboratory as(String alias) {
        return new ReserveLaboratory(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReserveLaboratory as(Name alias) {
        return new ReserveLaboratory(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ReserveLaboratory rename(String name) {
        return new ReserveLaboratory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReserveLaboratory rename(Name name) {
        return new ReserveLaboratory(name, null);
    }
}
