/*
 * This file is generated by jOOQ.
 */
package com.dw2.reserva.persistence.jooq.tables;


import com.dw2.reserva.persistence.jooq.DefaultSchema;
import com.dw2.reserva.persistence.jooq.Indexes;
import com.dw2.reserva.persistence.jooq.tables.records.ReserveEquipmentRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReserveEquipment extends TableImpl<ReserveEquipmentRecord> {

    private static final long serialVersionUID = 104095302;

    /**
     * The reference instance of <code>reserve_equipment</code>
     */
    public static final ReserveEquipment RESERVE_EQUIPMENT = new ReserveEquipment();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReserveEquipmentRecord> getRecordType() {
        return ReserveEquipmentRecord.class;
    }

    /**
     * The column <code>reserve_equipment.id</code>.
     */
    public final TableField<ReserveEquipmentRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>reserve_equipment.start_date</code>.
     */
    public final TableField<ReserveEquipmentRecord, LocalDateTime> START_DATE = createField("start_date", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * The column <code>reserve_equipment.end_date</code>.
     */
    public final TableField<ReserveEquipmentRecord, LocalDateTime> END_DATE = createField("end_date", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * The column <code>reserve_equipment.user_id</code>.
     */
    public final TableField<ReserveEquipmentRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>reserve_equipment.equipment_id</code>.
     */
    public final TableField<ReserveEquipmentRecord, Integer> EQUIPMENT_ID = createField("equipment_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>reserve_equipment</code> table reference
     */
    public ReserveEquipment() {
        this(DSL.name("reserve_equipment"), null);
    }

    /**
     * Create an aliased <code>reserve_equipment</code> table reference
     */
    public ReserveEquipment(String alias) {
        this(DSL.name(alias), RESERVE_EQUIPMENT);
    }

    /**
     * Create an aliased <code>reserve_equipment</code> table reference
     */
    public ReserveEquipment(Name alias) {
        this(alias, RESERVE_EQUIPMENT);
    }

    private ReserveEquipment(Name alias, Table<ReserveEquipmentRecord> aliased) {
        this(alias, aliased, null);
    }

    private ReserveEquipment(Name alias, Table<ReserveEquipmentRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.RESERVE_EQUIPMENT_PRIMARY, Indexes.RESERVE_EQUIPMENT_RESERVE_EQUIPMENT_FK_EQUIPMENT, Indexes.RESERVE_EQUIPMENT_RESERVE_EQUIPMENT_FK_USER);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ReserveEquipmentRecord, Integer> getIdentity() {
        return Internal.createIdentity(com.dw2.reserva.persistence.jooq.tables.ReserveEquipment.RESERVE_EQUIPMENT, com.dw2.reserva.persistence.jooq.tables.ReserveEquipment.RESERVE_EQUIPMENT.ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ReserveEquipmentRecord> getPrimaryKey() {
        return Internal.createUniqueKey(com.dw2.reserva.persistence.jooq.tables.ReserveEquipment.RESERVE_EQUIPMENT, "KEY_reserve_equipment_PRIMARY", com.dw2.reserva.persistence.jooq.tables.ReserveEquipment.RESERVE_EQUIPMENT.ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ReserveEquipmentRecord>> getKeys() {
        return Arrays.<UniqueKey<ReserveEquipmentRecord>>asList(
              Internal.createUniqueKey(com.dw2.reserva.persistence.jooq.tables.ReserveEquipment.RESERVE_EQUIPMENT, "KEY_reserve_equipment_PRIMARY", com.dw2.reserva.persistence.jooq.tables.ReserveEquipment.RESERVE_EQUIPMENT.ID)
        );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReserveEquipment as(String alias) {
        return new ReserveEquipment(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReserveEquipment as(Name alias) {
        return new ReserveEquipment(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ReserveEquipment rename(String name) {
        return new ReserveEquipment(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReserveEquipment rename(Name name) {
        return new ReserveEquipment(name, null);
    }
}
