create table laboratory (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  name VARCHAR(50) not null
);

insert into laboratory (id, name) values
(1, 'Laboratório 1'),
(2, 'Laboratório 2');
