create table user (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  name VARCHAR(50) not null,
  email VARCHAR(50) not null,
  cpf VARCHAR(50) not null,
  type VARCHAR(50) not null
);

insert into user (id, name, email, cpf, type) values
(1, 'Carlos Alves', 'carlos.alves@gmail.com', '448.548.854-12', 'TEACHER'),
(2, 'Tiago Santos', 'tiago.santos@gmail.com', '325.845.554-44', 'TEACHER'),
(3, 'Rafael Gomes', 'rafael.gomes@gmail.com', '236.887.541-56', 'STUDENT'),
(4, 'João Andrade', 'joao.andrade@gmail.com', '558.874.651-99', 'STUDENT'),
(5, 'Igor Neves', 'igor.neves@gmail.com', '985.232.478-59', 'STUDENT');
