create table reserve_laboratory (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  start_date TIMESTAMP NOT NULL,
  end_date TIMESTAMP NOT NULL,
  user_id INTEGER not null,
  laboratory_id INTEGER not null,

  foreign key (user_id) references user (id),
  foreign key (laboratory_id) references laboratory (id)
);

insert into reserve_laboratory (id, start_date, end_date, user_id, laboratory_id) values
(1, '2019-10-20 10:00:00', '2019-10-20 15:00:00', 1, 2),
(2, '2019-11-20 09:30:00', '2019-11-20 13:30:00', 2, 1);
