create table reserve_equipment (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  start_date TIMESTAMP NOT NULL,
  end_date TIMESTAMP NOT NULL,
  user_id INTEGER not null,
  equipment_id INTEGER not null,

  foreign key (user_id) references user (id),
  foreign key (equipment_id) references equipment (id)
);

insert into reserve_equipment (id, start_date, end_date, user_id, equipment_id) values
(1, '2019-10-10 10:00:00', '2019-10-10 11:00:00', 3, 1),
(2, '2019-11-10 09:30:00', '2019-11-10 10:30:00', 4, 2);
